version: '1.0'

services:
  llm_chatbot-app: # You can name your service whatever you like; "streamlit-app" is just a placeholder.
    build:
      context: ../chatbot  # Assuming your Dockerfile is inside an 'app' directory.
    ports:
      - "${STREAMLIT_PORT}:8007"  # Replace with "host_port:container_port" if your application needs to expose any ports.
    volumes:
      - .:/var/www  # Adjust this if your app directory structure is different.
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:${STREAMLIT_PORT}/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 5
